spring:

  jackson:
    serialization:
      fail-on-empty-beans: off
  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true



  mvc:
    path match:
      matching-strategy: ant_path_matcher


  jpa:
    properties:
      hibernate:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jjungminleedb.cqyg29mvueow.ap-northeast-2.rds.amazonaws.com:3306/tinyPoof?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: monggeul
    password: monggeul1234!



gemini:
  iss: tinypoof@tinypoof.iam.gserviceaccount.com
  model-name: gemini-pro-vision
  region: asia-northeast3
  project-id: tinypoof
  private-key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCXSQLWPWrXt/dV\n0+J7M6G/fYl4odRYeBGvVCu7OUrxypNN5yCCBYcoDM/vPzeB9M4C+UbrV+2U/Ih5\npiacGoMsJpZgKhr6M8ESEXtNcxFyn/NbcxauhgArUsdtXhLt86TrVNl5RWA7LJjM\nZZvvtJ+FF82aJW5N+l1yZl8QbB9V7DTnkd+uSS5+qaKPzAHV0ktw6qamuhiAr81n\ndmfxSXJ7bZOh+8Ba8h87iR9VLyeVmg0ftkyE+Pasdn5E8GWjj+iZLYSk6GX+8czC\ncljaZYqfMiHiI7FeU66UVzusxG2s0qJQU0FVFkPlRboVEVA1FGnPgJJh0LLIWDYF\nwEhX9Cb7AgMBAAECggEAFt2krZ/70Z4PJqxPW4K6zFgbmp2PHE4Nkjv9Hh+zOad+\nKzSnX6+ZNY72MLmT2LMZHi7yLqkMEkw3Dnfz9v003Uv5x5AlorKG2IXG5rZhKTuO\ny0Ayae98ABBTby7cWpXMU/tvoVpAiMEdWSt0bb8Vq0alP0qwCN4yGJPrg25sMA63\nlK5M0qIKkjOnku1RE2Q161CynpTmIkLutPt1rlptzk3qlVI1rR9N2h3U4DCfpe4/\n1mhsXwCHWbGLnjX0Iz3tyCww5U/yz2+lFUEy6N389inx7LGgeOL2F1mBBLS0CtoK\nx1kS3VuZbOhHRgx21SRNmf0SPvDG0WBZEMv8JoQKQQKBgQDFyjnAt2xR6vtEC2/l\nCInDdzysEZ+h7/fiz1OOeQ28acdsdHUH/S+UnKxYHUdCiLMcfnz1vBPrGBDyV79Z\nmGaws5LXkrgKwNU0OBf1t212AOpH6CQ+MSzQDr1ZmUg3SvINNvLk4UTVyDVZiJZe\nKGFKaIOrjO4C3J9Bwhzf3I4XwQKBgQDDzw1dzmg4qp/+IP3Yei/NmVeb7wPUuX+4\nC5CoSv12FeUI8mZm7CmBbAxEZPPM2ItaoDWVmd+sZw4/6Xsoxv7Bcz6DhsAZTdbN\nk00CNMP1CF+m1xS6dFQcMOuHR6iyZPn1RLH1c7c0LvtPNjTBcmFbsHiz0JT0OR8k\ny8IwofQNuwKBgGcxsFolGQXQdNI2qWW0w7PQ9T3NYB0sR4f1peGytQD1q4+hXyIQ\n7g86gwziEbjb+59FO0s2mqnQ/56BO5uyUPmmZ1nD+fPaUiKRlaak0h58Mb/clXRB\nUeEnn5Es0SnQF2PfpHDYO4LSl0skYVe097XLu874k4G4u/qiHVCLETPBAoGBAJu4\nEwIx/zJphxlb9WRuL4wLUeABogNPjmG4WM9t68o4OU/3LjbVw2BYpBzUSAr1f0WQ\nOW0C1R3PS0bKkJZqQvlnhCSnSigVfik45rpFaj147lDJpYNuteFBil2oQGG26g4D\nFp+D6gOHBXcGPchGBWUcn7EoxPzAXKMvo/x3H5a3AoGBAJkARdEInvY4rtG4dW1u\nS+XkCr1N38YD4Br0ceZzGInjgw0cj0OCRoWVf843tcc12hNWs7tLa2XRP1g6Rm5K\nwoBr/4ukocU8wIsusiUsT34doEB+ISAwhma6fQJoms29f59rJB2KwAo1qWbi87wt\nlJZ0rR0KsZE3uz8WDSNjf6lI\n-----END PRIVATE KEY-----\n"


cloud:
  aws:
    s3:
      store-dir: tinypoof/baby
      bucket: jungminbucket2
      base-url: https://jungminbucket2.s3.ap-northeast-2.amazonaws.com/

    region:
      static: ap-northeast-2
      auto: false

    credentials:
      access-key: AKIAYBNBDPUT7PMEDJLK
      secret-key: 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

    stack:
      auto: false